In [13]:
import numpy as np
import cv2 as cv
import glob
from PIL import Image 

print('opencv:' , cv.__version__)
print('numpy :', np.__version__)

#set np printout options
np.set_printoptions(suppress=True,
                    formatter={'float_kind': '{:f},'.format})

opencv: 4.6.0
numpy : 1.21.5


In [25]:


# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((9*14,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:14].T.reshape(-1,2)#set np printout options
np.set_printoptions(suppress=True,
                    formatter={'float_kind': '{:f}'.format})
# Arrays to store object points and image points from all the images.

objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
images = glob.glob('/home/werner/Projects/open_cv/calibration_photos/*.jpg')

for fname in images:
    # print(fname)
    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (9,14), None)
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners)
        # Draw and display the corners
        # cv.drawChessboardCorners(img, (9,14), corners2, ret)
        # cv.imshow('img', img)
        # cv.waitKey(500)

cv.destroyAllWindows()


ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)


img = cv.imread(fname)
h,  w = img.shape[:2]
newcameramtx, roi = cv.getOptimalNewCameraMatrix(mtx, dist, (w,h), 1, (w,h))

#Field of view calculation.
fx = mtx[0][0] 
fy = mtx[1][1]
fov_x = 2 * np.arctan2(w, 2 * fx)
fov_y = 2 * np.arctan2(h, 2 * fy)

print(mtx)
print('Image with: ', w)
print('Image height: ', h)
print(f"{fov_x = :.1f} rad")
print(f"{fov_y = :.1f} rad")

#write to output
output_file = open('calibration_output.txt', 'w')
output_file.write(str(mtx) + '\n\n')
output_file.write('w: ' + str(w) + '(pixels)' + '\n')
output_file.write('h: ' + str(h) + '(pixels)'+ '\n\n')
output_file.write('fov_x: ' + str(fov_x) + '(rad)'+ '\n')
output_file.write('fov_y: ' + str(fov_y) + '(rad)'+ '\n')
output_file.close()

#Save matrix for use in opencv to opengl
np.savetxt(fname='camera_matrix.txt',X=mtx, delimiter=',', header='opencv_matrix')

info = np.array([
   [w,h]
], dtype=np.float64)

np.savetxt(fname='image_info.txt',X=info, delimiter=',',header='width, height')





QObject::moveToThread: Current thread (0x5649a12f1800) is not the object's thread (0x5649a35fda90).
Cannot move to target thread (0x5649a12f1800)

QObject::moveToThread: Current thread (0x5649a12f1800) is not the object's thread (0x5649a35fda90).
Cannot move to target thread (0x5649a12f1800)

QObject::moveToThread: Current thread (0x5649a12f1800) is not the object's thread (0x5649a35fda90).
Cannot move to target thread (0x5649a12f1800)

QObject::moveToThread: Current thread (0x5649a12f1800) is not the object's thread (0x5649a35fda90).
Cannot move to target thread (0x5649a12f1800)

QObject::moveToThread: Current thread (0x5649a12f1800) is not the object's thread (0x5649a35fda90).
Cannot move to target thread (0x5649a12f1800)

QObject::moveToThread: Current thread (0x5649a12f1800) is not the object's thread (0x5649a35fda90).
Cannot move to target thread (0x5649a12f1800)

QObject::moveToThread: Current thread (0x5649a12f1800) is not the object's thread (0x5649a35fda90).
Cannot move to tar

[[3549.288187 0.000000 1724.224632]
 [0.000000 3551.909378 2289.571598]
 [0.000000 0.000000 1.000000]]
Image with:  3472
Image height:  4624
fov_x = 0.9 rad
fov_y = 1.2 rad


In [ ]:
# undistort
dst = cv.undistort(img, mtx, dist, None, newcameramtx)
# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult.png', dst)

True

In [ ]:
# undistort
mapx, mapy = cv.initUndistortRectifyMap(mtx, dist, None, newcameramtx, (w,h), 5)
dst = cv.remap(img, mapx, mapy, cv.INTER_LINEAR)
# crop the image
x, y, w, h = roi
dst = dst[y:y+h, x:x+w]
cv.imwrite('calibresult2.png', dst)

True